### ISSUE TITLE
Add ecoCode-android plugin to SonarQube Marketplace

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode-mobile#67]
(I'm creating this issue to track activity regarding this plugin deployment target on SonarQube Marketplace. You can assign this issue to me.)

In the same way as what had been done for the non-mobile plugins (green-code-initiative/ecoCode#63), this plugin should be published on the SonarQube Marketplace.

TODO List:
- [ ] Rename repository to `ecoCode-android` (see: #64)
- [ ] Centralized rules description use by this plugin (see: #92)
- [ ] Rename rule IDs to follow convention (`EC` prefix followed by a number) (Do not forget to add `@DeprecatedRuleKey` annotation when needed)
- [ ] Check license is a [Free-Libre / Open Source Software License](http://opensource.org/licenses)
- [ ] Check documentation is available online in English
- [ ] Release 1.1.0 (see: #2) with a release notes that reflect all significant changes in the version
- [x] Check plugin key (must be short and unique, lowercase, no camelcase, composed only of [a-z0-9], related to the name of your plugin not just the name of a language - e.g. cannot be java, rust, js/javascript, …)
    - [`ecocodeandroid`](https://github.com/green-code-initiative/ecoCode-mobile/blob/1.0.1/android-plugin/pom.xml#LL224C17-L224C31)
- [ ] Check plugin description (must not be misleading in terms of content, the code needs to do pretty much what the name and description say it does)
- [ ] Provide the necessary details to be able to test the plugin
- [ ] Check [SonarCloud](https://sonarcloud.io/) quality gate is green when doing a release
- [ ] Check platform requirements (it runs on JRE 11 with SonarQube 9 LTS and 10)
- [x] Check no export of files to other servers / services from within SonarQube or during SonarQube analysis
- [ ] Create discussion on SonarSource community

More information:
* [Sonarsource community - Deploying to the Marketplace](https://community.sonarsource.com/t/deploying-to-the-marketplace/35236)
* [github/sonar-update-center-properties](https://github.com/SonarSource/sonar-update-center-properties)

**Comment by dedece35** [comment]
Hi @jycr, thank you for issue.
plop @glalloue @olegoaer @jhertout

**Comment by jhertout** [comment]
Hi, for the rule naming convention, do we begin at a very high number, such as 10000 to simplify the management with the ecoCode repo and avoid conflict?
Our first rule will be EC10001 for example?

What do you think @olegoaer, @jycr, @dedece35?

**Comment by jycr** [comment]
> Hi, for the rule naming convention, do we begin at a very high number, such as 10000 to simplify the management with the ecoCode repo and avoid conflict? Our first rule will be EC10001 for example?
> 
> What do you think @olegoaer, @jycr, @dedece35?

Oops, I've already started refactoring for Android rules starting numbering at EC500 and for iOS rules at EC600.

**Comment by jycr** [comment]
I have found common "legacy keys" for Android and iOS :

* EIDL001
* EIDL002
* EPOW002
* ESOB001
* ESOB002
* ESOB003
* ESOB005
* ESOB006

There are same keys, but not same description. For example:


**[For `EIDL001` on iOS](https://github.com/green-code-initiative/ecoCode-ios/blob/1.1.0/swift-lang/src/main/resources/ecocode-swift-rules.json#L3-L17)**

```json
{
  "key": "EIDL001",
  "name": "Idle timer disabled",
  "severity": "MAJOR",
  "description": "Do not disable idle timer, unless absolutely necessary.",
  "debt": {"function": "CONSTANT_ISSUE", "offset": "5min"},
  "tags": ["ecocode", "environment", "sobriety", "eco-design"],
  "type": "CODE_SMELL"
}
```

**[For `EIDL001` on Android](https://github.com/green-code-initiative/ecoCode-android/blob/1.0.1/android-plugin/src/main/resources/org/sonar/l10n/java/rules/squid/EIDL001_java.json#L2-L15)**

```json
{
  "title": "Idleness: Keep Screen On (addFlags)",
  "type": "CODE_SMELL",
  "status": "ready",
  "remediation": {"func": "Constant/Issue", "constantCost": "20min"},
  "tags": ["idleness", "environment", "ecocode", "android"],
  "defaultSeverity": "Major"
}
```

So, we must not use same new "ECxxxx" keys? You agree?

**Comment by jhertout** [comment]
> > Hi, for the rule naming convention, do we begin at a very high number, such as 10000 to simplify the management with the ecoCode repo and avoid conflict? Our first rule will be EC10001 for example?
> > What do you think @olegoaer, @jycr, @dedece35?
> 
> Oops, I've already started refactoring for Android rules starting numbering at EC500 and for iOS rules at EC600.

Is it easy for you to start at EC10000 and EC20000? I think it is possible that someday we will have 100 rules and if for a reason or an other we have to drop numbers, it will be easier. 
In which project do you start refactoring? The documentation? I was planning to start doing it on ecoCode-Android.

Thanks

**Comment by jhertout** [comment]
> I have found common "legacy keys" for Android and iOS :
> 
> * EIDL001
> * EIDL002
> * EPOW002
> * ESOB001
> * ESOB002
> * ESOB003
> * ESOB005
> * ESOB006
> 
> There are same keys, but not same description. For example:
> 
> **[For `EIDL001` on iOS](https://github.com/green-code-initiative/ecoCode-ios/blob/1.1.0/swift-lang/src/main/resources/ecocode-swift-rules.json#L3-L17)**
> 
> ```json
> {
>   "key": "EIDL001",
>   "name": "Idle timer disabled",
>   "severity": "MAJOR",
>   "description": "Do not disable idle timer, unless absolutely necessary.",
>   "debt": {"function": "CONSTANT_ISSUE", "offset": "5min"},
>   "tags": ["ecocode", "environment", "sobriety", "eco-design"],
>   "type": "CODE_SMELL"
> }
> ```
> 
> **[For `EIDL001` on Android](https://github.com/green-code-initiative/ecoCode-android/blob/1.0.1/android-plugin/src/main/resources/org/sonar/l10n/java/rules/squid/EIDL001_java.json#L2-L15)**
> 
> ```json
> {
>   "title": "Idleness: Keep Screen On (addFlags)",
>   "type": "CODE_SMELL",
>   "status": "ready",
>   "remediation": {"func": "Constant/Issue", "constantCost": "20min"},
>   "tags": ["idleness", "environment", "ecocode", "android"],
>   "defaultSeverity": "Major"
> }
> ```
> 
> So, we must not use same new "ECxxxx" keys? You agree?

Yes it is an error, we must not use same new "ECxxxx" keys.

**Comment by jhertout** [comment]
The plugin was accepted on SonarQube market place : https://community.sonarsource.com/t/new-plugin-ecocode-android-requesting-inclusion-in-sonarqube-marketplace/104674. I close this issue.
